# Generated by Django 3.2.12 on 2023-02-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_event_registration_event_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_registration',
            name='date',
        ),
    ]
