# Generated by Django 3.2.12 on 2023-02-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_event_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_registration',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event_registration',
            name='event_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
