# Generated by Django 3.2.12 on 2023-02-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20230204_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_registration',
            name='student_number',
            field=models.PositiveBigIntegerField(default=99999),
            preserve_default=False,
        ),
    ]
