# Generated by Django 3.2.12 on 2023-02-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_student_registration_student_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_registration',
            name='student_number',
            field=models.PositiveIntegerField(default=99999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='student_number',
            field=models.PositiveIntegerField(),
        ),
    ]
