# Generated by Django 4.0.4 on 2023-02-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_rename_student_number_staff_registration_staff_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='event_registration',
            name='event_contact',
            field=models.PositiveIntegerField(default=9999999999999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event_registration',
            name='event_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='staff_registration',
            name='faculty_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff_registration',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
