# Generated by Django 4.0.4 on 2023-02-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_courses_event_registration_event_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_registration',
            name='event_contact',
            field=models.CharField(max_length=1000),
        ),
    ]
